
package GUI;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JTextField;
import main.Class.DAO.ContactDAO;
import main.Class.Implements.ContactImp;

public class AddGUI extends javax.swing.JFrame {


    ContactImp contact = new ContactImp();
    ContactDAO contactDAO = new ContactDAO();
    
    public AddGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        surnameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        landLabel = new javax.swing.JLabel();
        mobile1Label = new javax.swing.JLabel();
        mobile2Label = new javax.swing.JLabel();
        IdFamilyLabel = new javax.swing.JLabel();
        divisionLabel = new javax.swing.JLabel();
        postLabel = new javax.swing.JLabel();
        postField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        landField = new javax.swing.JTextField();
        mobile1Field = new javax.swing.JTextField();
        mobile2Field = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        divisionBox = new javax.swing.JComboBox<>();
        message = new javax.swing.JLabel();
        dateField = new com.toedter.calendar.JDateChooser();
        idFamilyField = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 550));
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(154, 159, 0));
        Header.setPreferredSize(new java.awt.Dimension(500, 50));
        Header.setLayout(new java.awt.BorderLayout());

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(240, 240, 240));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("ADD A CONTACT");
        Header.add(title, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Dashboard.setBackground(new java.awt.Color(4, 9, 84));
        Dashboard.setPreferredSize(new java.awt.Dimension(500, 450));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        surnameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        surnameLabel.setForeground(new java.awt.Color(240, 240, 240));
        surnameLabel.setText("Surname");
        Dashboard.add(surnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(240, 240, 240));
        nameLabel.setText("Name");
        Dashboard.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(240, 240, 240));
        dateLabel.setText("Date of Birth");
        Dashboard.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(240, 240, 240));
        addressLabel.setText("Address");
        Dashboard.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        landLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        landLabel.setForeground(new java.awt.Color(240, 240, 240));
        landLabel.setText("Land Phone");
        Dashboard.add(landLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        mobile1Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mobile1Label.setForeground(new java.awt.Color(240, 240, 240));
        mobile1Label.setText("Mobile 1");
        Dashboard.add(mobile1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        mobile2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mobile2Label.setForeground(new java.awt.Color(240, 240, 240));
        mobile2Label.setText("Mobile 2");
        Dashboard.add(mobile2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        IdFamilyLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IdFamilyLabel.setForeground(new java.awt.Color(240, 240, 240));
        IdFamilyLabel.setText("ID Family");
        Dashboard.add(IdFamilyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        divisionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        divisionLabel.setForeground(new java.awt.Color(240, 240, 240));
        divisionLabel.setText("Division");
        Dashboard.add(divisionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        postLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        postLabel.setForeground(new java.awt.Color(240, 240, 240));
        postLabel.setText("Post");
        Dashboard.add(postLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        postField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dashboard.add(postField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 320, 30));

        surnameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dashboard.add(surnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 320, 30));

        nameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dashboard.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 320, 30));

        addressField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dashboard.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 320, 30));

        landField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dashboard.add(landField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 320, 30));

        mobile1Field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dashboard.add(mobile1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 320, 30));

        mobile2Field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Dashboard.add(mobile2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 320, 30));

        add.setBackground(new java.awt.Color(3, 11, 116));
        add.setForeground(new java.awt.Color(240, 240, 240));
        add.setText("ADD");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        Dashboard.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 100, 30));

        cancel.setBackground(new java.awt.Color(3, 11, 116));
        cancel.setForeground(new java.awt.Color(240, 240, 240));
        cancel.setText("CANCEL");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        Dashboard.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 100, 30));

        divisionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matthew", "Marc", "Luke", "John" }));
        Dashboard.add(divisionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 160, 30));

        message.setForeground(new java.awt.Color(240, 240, 0));
        Dashboard.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 20));

        dateField.setDateFormatString("yyyy-MM-dd");
        Dashboard.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 270, 30));
        Dashboard.add(idFamilyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 140, 30));

        getContentPane().add(Dashboard, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(500, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changeColor(JButton hover, Color rand)
    {   
        hover.setBackground(rand);
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
    }//GEN-LAST:event_addActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        changeColor(cancel, new Color(4,9,84));
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        changeColor(cancel, new Color(3,11,116));
    }//GEN-LAST:event_cancelMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        contact.setSurname(surnameField.getText());
        contact.setName(nameField.getText());
        contact.setDateBirth(((JTextField)dateField.getDateEditor().getUiComponent()).getText());
        contact.setAddress(addressField.getText());
        contact.setPhone1(landField.getText());
        contact.setPhone2(mobile1Field.getText());
        contact.setPhone3(mobile2Field.getText());
        contact.setIdFamily(Integer.parseInt(idFamilyField.getValue().toString()));
        contact.setPost(postField.getText());
        
        String group = divisionBox.getSelectedItem().toString();
        
        if(group == "Matthew")
        {
            contact.setIdGroup(1);
        }
        else if(group == "Marc")
        {
            contact.setIdGroup(2);
        }
        else if(group == "Luke")
        {
            contact.setIdGroup(3);
        }
        else
        {
            contact.setIdGroup(4);
        }

        contactDAO.add(contact, message, HomeGUI.userLabel);

        
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        changeColor(add, new Color(4,9,84));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        changeColor(add, new Color(3,11,116));
    }//GEN-LAST:event_addMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel IdFamilyLabel;
    private javax.swing.JButton add;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> divisionBox;
    private javax.swing.JLabel divisionLabel;
    private javax.swing.JSpinner idFamilyField;
    private javax.swing.JTextField landField;
    private javax.swing.JLabel landLabel;
    private javax.swing.JLabel message;
    private javax.swing.JTextField mobile1Field;
    private javax.swing.JLabel mobile1Label;
    private javax.swing.JTextField mobile2Field;
    private javax.swing.JLabel mobile2Label;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField postField;
    private javax.swing.JLabel postLabel;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
