/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import main.Class.Functions;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;
import main.Class.User;
import main.Class.DAO.UserDAO;

/**
 *
 * @author prave
 */
public class LoginGUI extends javax.swing.JFrame {

    User user = new User();
    UserDAO userDAO = new UserDAO();

    Image icon = Toolkit.getDefaultToolkit().getImage("logo.png");    
    Functions function = new Functions();
    
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Header = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        ButtonClose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Menus = new javax.swing.JPanel();
        ButtonLoginRegister = new javax.swing.JPanel();
        LoginButton = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JPanel();
        RegisterLabel = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        PanelLogin = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        ButtonLogin = new javax.swing.JPanel();
        Connect = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PanelRegister = new javax.swing.JPanel();
        UsernameRegister = new javax.swing.JLabel();
        PasswordRegister = new javax.swing.JLabel();
        UsernameFieldRegister = new javax.swing.JTextField();
        ButtonRegister = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        messageRegister = new javax.swing.JLabel();
        NameFieldRegister = new javax.swing.JTextField();
        SurnameFieldRegister = new javax.swing.JTextField();
        NameRegister = new javax.swing.JLabel();
        SurnameRegister = new javax.swing.JLabel();
        PasswordFieldRegister = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("login"); // NOI18N
        setUndecorated(true);

        Header.setPreferredSize(new java.awt.Dimension(200, 100));
        Header.setLayout(new java.awt.GridBagLayout());

        Header1.setBackground(new java.awt.Color(4, 9, 84));
        Header1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Header1.setPreferredSize(new java.awt.Dimension(500, 50));
        Header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Header1MouseDragged(evt);
            }
        });
        Header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Header1MousePressed(evt);
            }
        });
        Header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonClose.setBackground(new java.awt.Color(4, 9, 84));
        ButtonClose.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonClose.setLayout(new java.awt.BorderLayout());

        Close.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Close.setForeground(new java.awt.Color(153, 153, 153));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setText("X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        ButtonClose.add(Close, java.awt.BorderLayout.CENTER);

        Header1.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Header.add(Header1, gridBagConstraints);

        Menus.setBackground(new java.awt.Color(4, 9, 84));
        Menus.setLayout(new java.awt.BorderLayout());

        ButtonLoginRegister.setBackground(new java.awt.Color(154, 159, 0));
        ButtonLoginRegister.setPreferredSize(new java.awt.Dimension(500, 50));
        ButtonLoginRegister.setLayout(new java.awt.GridLayout(1, 0));

        LoginButton.setBackground(new java.awt.Color(154, 159, 0));
        LoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 9, 84)));
        LoginButton.setLayout(new java.awt.BorderLayout());

        LoginLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(240, 240, 240));
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("LOGIN");
        LoginLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginLabelMouseExited(evt);
            }
        });
        LoginButton.add(LoginLabel, java.awt.BorderLayout.CENTER);

        ButtonLoginRegister.add(LoginButton);

        RegisterButton.setBackground(new java.awt.Color(154, 159, 0));
        RegisterButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 9, 84)));
        RegisterButton.setLayout(new java.awt.BorderLayout());

        RegisterLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(240, 240, 240));
        RegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterLabel.setText("REGISTER");
        RegisterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterLabelMouseExited(evt);
            }
        });
        RegisterButton.add(RegisterLabel, java.awt.BorderLayout.CENTER);

        ButtonLoginRegister.add(RegisterButton);

        Menus.add(ButtonLoginRegister, java.awt.BorderLayout.LINE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 332;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Header.add(Menus, gridBagConstraints);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Dashboard.setBackground(new java.awt.Color(4, 9, 84));
        Dashboard.setLayout(new java.awt.CardLayout());

        PanelLogin.setBackground(new java.awt.Color(4, 9, 84));
        PanelLogin.setForeground(new java.awt.Color(4, 9, 84));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(240, 240, 240));
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setText("USERNAME");
        PanelLogin.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(240, 240, 240));
        Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username.setText("PASSWORD");
        PanelLogin.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        UsernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelLogin.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, 40));

        ButtonLogin.setBackground(new java.awt.Color(154, 159, 0));
        ButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonLogin.setLayout(new java.awt.BorderLayout());

        Connect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Connect.setForeground(new java.awt.Color(240, 240, 240));
        Connect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Connect.setText("LOGIN");
        Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConnectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConnectMouseExited(evt);
            }
        });
        ButtonLogin.add(Connect, java.awt.BorderLayout.CENTER);

        PanelLogin.add(ButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 100, 50));

        message.setForeground(new java.awt.Color(240, 240, 0));
        PanelLogin.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 430, 20));

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelLogin.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 290, 40));

        Dashboard.add(PanelLogin, "card2");

        PanelRegister.setBackground(new java.awt.Color(4, 9, 84));
        PanelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsernameRegister.setForeground(new java.awt.Color(240, 240, 240));
        UsernameRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameRegister.setText("USERNAME");
        PanelRegister.add(UsernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        PasswordRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordRegister.setForeground(new java.awt.Color(240, 240, 240));
        PasswordRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordRegister.setText("PASSWORD");
        PanelRegister.add(PasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        UsernameFieldRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelRegister.add(UsernameFieldRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 290, 40));

        ButtonRegister.setBackground(new java.awt.Color(154, 159, 0));
        ButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRegister.setLayout(new java.awt.BorderLayout());

        Register.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Register.setForeground(new java.awt.Color(240, 240, 240));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setText("REGISTER");
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterMouseExited(evt);
            }
        });
        ButtonRegister.add(Register, java.awt.BorderLayout.CENTER);

        PanelRegister.add(ButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 100, 50));

        messageRegister.setForeground(new java.awt.Color(240, 240, 0));
        PanelRegister.add(messageRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 430, 20));

        NameFieldRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelRegister.add(NameFieldRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 290, 40));

        SurnameFieldRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelRegister.add(SurnameFieldRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 290, 40));

        NameRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameRegister.setForeground(new java.awt.Color(240, 240, 240));
        NameRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameRegister.setText("NAME");
        PanelRegister.add(NameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        SurnameRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SurnameRegister.setForeground(new java.awt.Color(240, 240, 240));
        SurnameRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SurnameRegister.setText("SURNAME");
        PanelRegister.add(SurnameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        PasswordFieldRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelRegister.add(PasswordFieldRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 290, 40));

        Dashboard.add(PanelRegister, "card3");

        getContentPane().add(Dashboard, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(500, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color rand)
    {   
        hover.setBackground(rand);
    }
    
    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        changeColor(ButtonClose, new Color(228, 4, 4));
        Close.setForeground(new Color(240, 240, 240));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        changeColor(ButtonClose, new Color(4,9,84));
        Close.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_CloseMouseExited

    private void ConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectMouseClicked

        int right = userDAO.connect(user, UsernameField, PasswordField, this, message);

        switch (right) 
        {
            case 1:
                HomeGUI.userLabel.setText(UsernameField.getText());
                
                break;
            case 2:
                HomeGUI.ButtonActions.setVisible(false);
                HomeGUI.userLabel.setText(UsernameField.getText());
                break;
            case 3:
                HomeGUI.ButtonActions.setVisible(false);
                HomeGUI.AddDeleteUpdatePanelFinances.setVisible(false);
                HomeGUI.userLabel.setText(UsernameField.getText());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_ConnectMouseClicked

    private void ConnectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectMouseEntered
        changeColor(ButtonLogin, new Color(91, 88, 1));
    }//GEN-LAST:event_ConnectMouseEntered

    private void ConnectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectMouseExited
        changeColor(ButtonLogin, new Color(154, 159, 0));
    }//GEN-LAST:event_ConnectMouseExited

    private void RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseClicked
        user.setNameUser(NameFieldRegister.getText());
        user.setSurnameUser(SurnameFieldRegister.getText());
        user.setUsername(UsernameFieldRegister.getText());
        user.setPassword(PasswordFieldRegister.getText());
        
        userDAO.addUser(user, message, messageRegister, PanelLogin, PanelRegister);
    }//GEN-LAST:event_RegisterMouseClicked

    private void RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseEntered
        changeColor(ButtonRegister, new Color(91, 88, 1));
    }//GEN-LAST:event_RegisterMouseEntered

    private void RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseExited
        changeColor(ButtonRegister, new Color(154, 159, 0));
    }//GEN-LAST:event_RegisterMouseExited

    private void LoginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLabelMouseClicked
        PanelRegister.setVisible(false);
        PanelLogin.setVisible(true);   
    }//GEN-LAST:event_LoginLabelMouseClicked

    private void LoginLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLabelMouseEntered
        changeColor(LoginButton, new Color(91, 88, 1));
    }//GEN-LAST:event_LoginLabelMouseEntered

    private void LoginLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLabelMouseExited
        changeColor(LoginButton, new Color(154, 159, 0));
    }//GEN-LAST:event_LoginLabelMouseExited

    private void RegisterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseClicked
        PanelLogin.setVisible(false);
        PanelRegister.setVisible(true);
        
    }//GEN-LAST:event_RegisterLabelMouseClicked

    private void RegisterLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseEntered
        changeColor(RegisterButton, new Color(91, 88, 1));
    }//GEN-LAST:event_RegisterLabelMouseEntered

    private void RegisterLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLabelMouseExited
        changeColor(RegisterButton, new Color(154, 159, 0));
    }//GEN-LAST:event_RegisterLabelMouseExited
    
    static int xx, yy;
    private void Header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_Header1MousePressed

    private void Header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Header1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_Header1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel ButtonLogin;
    private javax.swing.JPanel ButtonLoginRegister;
    private javax.swing.JPanel ButtonRegister;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Connect;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header1;
    private javax.swing.JPanel LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel Menus;
    private javax.swing.JTextField NameFieldRegister;
    private javax.swing.JLabel NameRegister;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelRegister;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordFieldRegister;
    private javax.swing.JLabel PasswordRegister;
    private javax.swing.JLabel Register;
    private javax.swing.JPanel RegisterButton;
    private javax.swing.JLabel RegisterLabel;
    public static javax.swing.JTextField SurnameFieldRegister;
    private javax.swing.JLabel SurnameRegister;
    private javax.swing.JLabel Username;
    public static javax.swing.JTextField UsernameField;
    public static javax.swing.JTextField UsernameFieldRegister;
    private javax.swing.JLabel UsernameRegister;
    private javax.swing.JLabel message;
    private javax.swing.JLabel messageRegister;
    // End of variables declaration//GEN-END:variables
}
